### ISSUE TITLE
测试没成功

### ISSUE THREAD

**Issue by hyy34** [ukuq/onepoint#1]
返回404，我想问下，是不是只能是A1？E5可以吗！？
我看，postRawUr里有a1的表述。。

而且必须要建立个文件夹分享吗？根目录如何弄呢？

**Comment by ukuq** [comment]
e5我没有试过, 我用a1,e3 测试的都没有问题.
像这个链接
https://<$1>/personal/<$2>/_api/web/GetList(@a1)/RenderListDataAsStream?@a1='/personal/<$2>/Documents'&RootFolder=/personal/<$2>/Documents/share"
其中的/share代表的就是你的onedrive,根目录下的share文件夹。如果你要用其他目录作为分享的根目录，比如/a/b/，那么这个/share就要改成/a/b才行。所以为了简化配置，我才建议使用根目录下的share文件夹分享

**Comment by hyy34** [comment]
> e5我没有试过, 我用a1,e3 测试的都没有问题.
> 像这个链接
> https://<$1>/personal/<$2>/_api/web/GetList(@A1)/RenderListDataAsStream?@A1='/personal/<$2>/Documents'&RootFolder=/personal/<$2>/Documents/share"
> 其中的/share代表的就是你的onedrive,根目录下的share文件夹。如果你要用其他目录作为分享的根目录，比如/a/b/，那么这个/share就要改成/a/b才行。所以为了简化配置，我才建议使用根目录下的share文件夹分享

啊！那可能没成功的原因就是分享文件夹的问题，请问，如果我不想建立分享文件夹，只想在根目录弄，那如何操作呢！？

**Comment by ukuq** [comment]
根目录下,如果你想分享一个文件夹/a,那么你将share改成a就行
如果是多个文件夹,将/share改成/就行

**Comment by hyy34** [comment]
> 根目录下,如果你想分享一个文件夹/a,那么你将share改成a就行
> 如果是多个文件夹,将/share改成/就行

你说的是postRawUrl吧？那shareUrl呢，如何得到？

**Comment by ukuq** [comment]
> > 根目录下,如果你想分享一个文件夹/a,那么你将share改成a就行
> > 如果是多个文件夹,将/share改成/就行
> 
> 你说的是postRawUrl吧？那shareUrl呢，如何得到？

配置文档里面写的有，就是到sharepoint里面分享文件，获得的那个链接就是shareurl

**Comment by hyy34** [comment]
> > > 根目录下,如果你想分享一个文件夹/a,那么你将share改成a就行
> > > 如果是多个文件夹,将/share改成/就行
> > 
> > 
> > 你说的是postRawUrl吧？那shareUrl呢，如何得到？
> 
> 配置文档里面写的有，就是到sharepoint里面分享文件，获得的那个链接就是shareurl

额，配置文档里是分享的share的文件夹得到的shareurl，我的意思我想在根目录分享文件，那么我就没有shareurl啊。。。额，不知道说明白没！！

**Comment by hyy34** [comment]
测试下了，https://<$1>/personal/<$2>/_api/web/GetList(@A1)/RenderListDataAsStream?@A1='/personal/<$2>/Documents'&RootFolder=/personal/<$2>/Documents/写成这种，可以访问，但是只显示shareUrl的文件夹，而且文件夹点进去就404了。。。。

**Comment by ukuq** [comment]
> > > > 根目录下,如果你想分享一个文件夹/a,那么你将share改成a就行
> > > > 如果是多个文件夹,将/share改成/就行
> > > 
> > > 
> > > 你说的是postRawUrl吧？那shareUrl呢，如何得到？
> > 
> > 
> > 配置文档里面写的有，就是到sharepoint里面分享文件，获得的那个链接就是shareurl
> 
> 额，配置文档里是分享的share的文件夹得到的shareurl，我的意思我想在根目录分享文件，那么我就没有shareurl啊。。。额，不知道说明白没！！

分享其他文件夹也一样，分享得到的直接链接就是shareurl，按格式代入得到的链接就是postRawUrl

**Comment by ukuq** [comment]
你发一下demo

**Comment by hyy34** [comment]
> 你发一下demo

https://service-cyd2wkxw-1256173306.ap-hongkong.apigateway.myqcloud.com/release/onePoint

**Comment by ukuq** [comment]
> > 你发一下demo
> 
> https://service-cyd2wkxw-1256173306.ap-hongkong.apigateway.myqcloud.com/release/onePoint

你分享的这个文件夹所在的路径发我一下

**Comment by hyy34** [comment]
我的意思是，我想分享根目录下所有的文件和文件夹，postRawUrl可以写成"\"，但是shareUrl如何弄。

**Comment by hyy34** [comment]
> > > 你发一下demo
> > 
> > 
> > https://service-cyd2wkxw-1256173306.ap-hongkong.apigateway.myqcloud.com/release/onePoint
> 
> 你分享的这个文件夹所在的路径发我一下

额。根目录。

**Comment by ukuq** [comment]
> 我的意思是，我想分享根目录下所有的文件和文件夹，postRawUrl可以写成""，但是shareUrl如何弄。

哦哦，这个简单。你分享文件时全选就行了

**Comment by hyy34** [comment]
> > 我的意思是，我想分享根目录下所有的文件和文件夹，postRawUrl可以写成""，但是shareUrl如何弄。
> 
> 哦哦，这个简单。你分享文件时全选就行了

额。全选之后没有“共享”按钮。。。

**Comment by ukuq** [comment]
> > > 我的意思是，我想分享根目录下所有的文件和文件夹，postRawUrl可以写成""，但是shareUrl如何弄。
> > 
> > 
> > 哦哦，这个简单。你分享文件时全选就行了
> 
> 额。全选之后没有“共享”按钮。。。选择2个以上就没有“共享”选项了。

刚注意到这个问题，你先尽量把文件夹移动到一个目录里面吧。我再看看有没有其他办法。

**Comment by hyy34** [comment]
> > > > 我的意思是，我想分享根目录下所有的文件和文件夹，postRawUrl可以写成""，但是shareUrl如何弄。
> > > 
> > > 
> > > 哦哦，这个简单。你分享文件时全选就行了
> > 
> > 
> > 额。全选之后没有“共享”按钮。。。选择2个以上就没有“共享”选项了。
> 
> 刚注意到这个问题，你先尽量把文件夹移动到一个目录里面吧。我再看看有没有其他办法。

我感觉应该直接就弄成分享根目录所有文件就方便了。。之前都是把文件和文件夹放在根目录了。

**Comment by ukuq** [comment]
> > > > > 我的意思是，我想分享根目录下所有的文件和文件夹，postRawUrl可以写成""，但是shareUrl如何弄。
> > > > 
> > > > 
> > > > 哦哦，这个简单。你分享文件时全选就行了
> > > 
> > > 
> > > 额。全选之后没有“共享”按钮。。。选择2个以上就没有“共享”选项了。
> > 
> > 
> > 刚注意到这个问题，你先尽量把文件夹移动到一个目录里面吧。我再看看有没有其他办法。
> 
> 我感觉应该直接就弄成分享根目录所有文件就方便了。。之前都是把文件和文件夹放在根目录了。

我觉得还是弄成一个文件夹专供分享用合适些，毕竟你不可能一个盘里面都是需要分享的内容，保留一点私人空间总是好的。
