### ISSUE TITLE
使用onepoint配置工具绑定世纪互联失败

### ISSUE THREAD

**Issue by BrunuhVille** [ukuq/onepoint#12]
onepoint配置工具
[映射路径：/            ][云盘密码：空         ][模块类型：onedrive_garph]
[根路径(root)：空       ][  认证类型：1   ][  获取令牌：世纪互联读写   ]

访问ip:8020后显示
{"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid
...,"error_codes":[9002313]
"error_uri":"https://login.partner.microsoftonline.cn/error?code=9002313"
点开这个网址显示
Error Code | 9002313
Message | Invalid request. Request is malformed or invalid.
Remediation | Developer error - the app is attempting to sign in without the necessary or correct authentication parameters.
是什么问题呢，我该如何做？

**Comment by ukuq** [comment]
~~~
"funcName": "onedrive_graph",
"spConfig": {
    "refresh_token": "填写 refresh_token, 注意不要复制多了",
    "oauth": 1
},
~~~
参考这个吧，配置项看着没啥问题。
