### ISSUE TITLE
目前没有上传文件功能？

### ISSUE THREAD

**Issue by BrunuhVille** [ukuq/onepoint#14]
网页上传文件到网盘？

**Comment by ukuq** [comment]
视模块而定 onedrive_graph 和 system_fs 两个模块支持上传，其他模块暂不支持。

**Comment by BrunuhVille** [comment]
该如何使用这个功能呢。您可以示范一下么，用onedrive_graph

**Comment by BrunuhVille** [comment]
@ukuq 该如何使用这个功能呢。您可以示范一下么，用onedrive_graph

**Comment by ukuq** [comment]
https://onepoint.ukuq.now.sh/admin/#/login

登录之后，找到管理页面卡，然后就可以进行上传了

**Comment by BrunuhVille** [comment]
@ukuq 想问下如果用http://ip:8020的话，后台管理地址是什么
（ 用域名是这个http://example.com/admin/ ）

**Comment by BrunuhVille** [comment]
谢谢大佬~，上传成功了
