### ISSUE TITLE
now部署出现bug

### ISSUE THREAD

**Issue by Ares-X** [ukuq/onepoint#17]
rt，进入主页后点击任意网盘链接跳转到错误url，域名后多出一个ip地址
![image](https://user-images.githubusercontent.com/30471149/87287340-90651d00-c52c-11ea-836e-6eda45e7b7f4.png)

**Comment by ukuq** [comment]
https://github.com/ukuq/onepoint/blob/449725e188b5abe0b6f145c5174659e1b0386605/test/nowsh/api/index_now.js#L8

因为 vscode 编辑器的问题，这里的内容没有保存上。正确参数的应该是
~~~
        let r = await op.handleRaw(req.method, req.url, req.headers, req.body, req.headers['x-real-ip'], '', req.query, req.cookies);
~~~

改正后的部署结果可参考 https://onepoint2.ukuq.vercel.app/
