### ISSUE TITLE
关于网站图标的问题

### ISSUE THREAD

**Issue by huanauh** [ukuq/onepoint#2]
在根目录放置了favicon.ico文件，js文件中也填了。但是网站还是不显示图标。目前我试过icon: "./favicon.ico",和icon: "favicon.ico",都不行。

**Comment by huanauh** [comment]
对了，favicon.ico应该是和index.js放一起，还是说放在onedrive的share目录里面呢？

**Comment by ukuq** [comment]
网站图标目前只支持http://超链接加载

**Comment by huanauh** [comment]
了解，收到，谢谢。
