### ISSUE TITLE
世纪互联的SharePoint如何绑定

### ISSUE THREAD

**Issue by wekingchen** [ukuq/onepoint#22]
请教大佬，使用世纪互联版的SharePoint应该如何绑定呢？

**Comment by ukuq** [comment]
打开管理页面，http://127.0.0.1/admin/#/setting/more

新增 OneDrive 云盘，oauth_type 需要选择为 cn，然后又可以分为两种情况。

通过 api 访问。点击 快速获取 callback_code 下面的世纪互联，获取到 code，粘贴到 callback_code，然后，api_url 那里填写 https://graph.microsoft.com/v1.0/drives/{drive-id}/ 或者 https://graph.microsoft.com/v1.0/sites/{site-id}/drive/ ，至于drive-id、site-id 可以通过 f12 控制台查看。（世纪互联未测试此功能，不过感觉没什么问题）

通过分享文件夹链接。部分 api 受限的用户可以使用此功能。分享文件夹，分享权限为任何人可读。callback_code、refresh_token两个选项空着，填写 share_url

添加完成后，记得点击保存。

**Comment by wekingchen** [comment]
模块内部发生了错误,invalid_grant:AADSTS70008: The provided authorization code or refresh token has expired due to inactivity. Send a new interactive authorization request for this user and resource. Trace ID: 7e9acc44-be5b-4b56-92a6-2630b87f4500 Correlation ID: 251e4f43-f67a-4af5-b2ac-4cfc0a45213d Timestamp: 2021-04-20 12:38:49Z

**Comment by wekingchen** [comment]
可以了，api_url格式用

**Comment by wekingchen** [comment]
可以了，api_url格式用
https://microsoftgraph.chinacloudapi.cn/v1.0/sites/{site-id}/drive/

通过https://od.xkx.me/sp.php获取site-id

**Comment by wekingchen** [comment]
换个机器访问时就不行了，好像是授权失效了，有什么办法可以刷新授权呢？
报错信息：

{
  "error": "ModuleError",
  "data": {
    "msg": "invalid_grant:AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.\r\nTrace ID: 91f53f44-04f9-440a-a7cd-c19aa1dc3e00\r\nCorrelation ID: 3249e156-a8bf-46b6-a6f0-0649cc8a979d\r\nTimestamp: 2021-04-20 12:59:57Z"
  },
  "message": "模块内部发生了错误,invalid_grant:AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.\r\nTrace ID: 91f53f44-04f9-440a-a7cd-c19aa1dc3e00\r\nCorrelation ID: 3249e156-a8bf-46b6-a6f0-0649cc8a979d\r\nTimestamp: 2021-04-20 12:59:57Z"
}

**Comment by ukuq** [comment]
使用的是cloudflare吗？这个自带缓存的，可以尝试在 http://127.0.0.1/admin/#/dashboard 页面重载服务器配置。

**Comment by ukuq** [comment]
记得把 callback_code 留空，这一项有点让人迷惑，以后考虑把这个去掉

**Comment by wekingchen** [comment]
试过好像不行，有点迷，不知道该才能自动刷新token。我是用的cloudflare的worker部署的

**Comment by ukuq** [comment]
是的，refresh_token 与获取 callback_code 时的 client_id、client_secret 是一一对应的，如果不使用网页提供的默认 client_id 和client_secret，都是需要手动填入的。

关于这一点，我打算以后明确标注一下（我以为大家都懂，毕竟都折腾这么久od了。

**Comment by wekingchen** [comment]
嗯，那获取 callback_code 时的client_id、client_secret是什么呢？我填进去应该就可以了吧

**Comment by ukuq** [comment]
你用的应该是 zfile 配置的client，把这两个填进去就可以了
    clientId: 4a72d927-1907-488d-9eb2-1b465c53c1c5
    clientSecret: Y9CEA=82da5n-y_]KAWAgLH3?R9xf7Uw

**Comment by wekingchen** [comment]
填进去没对：
模块内部发生了错误,invalid_client:AADSTS7000215: Invalid client secret is provided. Trace ID: 2d54e9bd-8d85-4392-9b42-07ac60315700 Correlation ID: a660873c-7e14-4db3-8751-376297276ba8 Timestamp: 2021-04-20 15:45:51Z

我用的是“快速获取callback_code”-“世纪互联”获取的callback_code

**Comment by ukuq** [comment]
https://login.chinacloudapi.cn/common/oauth2/v2.0/authorize?client_id=4a72d927-1907-488d-9eb2-1b465c53c1c5&response_type=code&redirect_uri=https://zfile.jun6.net/onedrive/china-callback&scope=offline_access%20User.Read%20Files.ReadWrite.All

使用这个获取refresh_token,  然后填这两个
clientId: 4a72d927-1907-488d-9eb2-1b465c53c1c5
clientSecret: Y9CEA=82da5n-y_]KAWAgLH3?R9xf7Uw

自带的client可能失效了，一直没账号就没再测试，zfile提供的这一个应该可以用，我刚试了没有问题。

**Comment by wekingchen** [comment]
这下可以了，这套client_id、client_secret原来对应的是refresh_token，刚才填的callback_code。太感谢了，这么晚了还帮我查问题，谢谢！！！

**Comment by ukuq** [comment]
刚好在线，举手之劳~
