### ISSUE TITLE
加密和隐藏相应文件或文件夹功能无效

### ISSUE THREAD

**Issue by SkyNetX007** [ukuq/onepoint#24]
部署方式：Cloudflare Workers

详细问题：
挂载 Onedrive 盘成功，但其中设置"hidden"参数隐藏文件或文件夹无效；对目录加密不起作用，且面板中无设置某个目录加密的选项。
查看了项目 [DEMO](https://onepoint.onesrc.workers.dev/)，其中演示的[隐藏](https://onepoint.onesrc.workers.dev/onedrive/onedrive/%E5%8A%9F%E8%83%BD/hidden/)未能隐藏相应文件夹；[加密](https://onepoint.onesrc.workers.dev/onedrive/onedrive/%E5%8A%9F%E8%83%BD/hidden/)也不起作用，且用自己的盘测试时无法启用加密，即未显示密码输入框与提示。

**Comment by ukuq** [comment]
隐藏、列表密码、云盘密码这三个功能都会自动检查有没有管理员cookie，如果确认是管理员，这三个自动失效。如果需要测试这些功能，需要清除已有cookie，或者干脆使用无痕浏览查看。

隐藏：
隐藏功能需要填写的是相对于云盘挂载位置的路径。以功能演示部分为例，该部分是一个挂载在 `/system/` 路径下的onedrive，需要隐藏的文件是`/system/hidden/a`（目录），`/system/hidden/a.docx`（文件），所以此处hidden需要填写的内容就是`["/hidden/a","/hidden/a.docx"]`。当然，如果挂载的位置是`/system/hidden/`，那就要填写`["/a","/a.docx"]`。注意下格式，以`/`开头，且结尾不能是`/`。

`/onedrive/onedrive/功能/hidden/` 路径并没有隐藏文件，是因为这个是挂载在`/onedrive/onedrive/`路径下的，没有配置hidden参数，和`/system/` 是两个不同的位置。（实际上就是一盘多挂，互不影响）

列表密码：
列表密码是自动检测 `.password=*` 文件（夹）。这一部分不需要额外配置什么参数，只需要在使用时在云盘里面新建一个文件即可。

**Comment by SkyNetX007** [comment]
是否考虑将加密用的 .password=xxx 改为直接读取 .password 文件内容，防止密码暴露在文件名中，增加安全性？

**Comment by ukuq** [comment]
目前的设计里面，`.password=*`对非管理员是不可见的，不用担心密码暴露的问题。

例如：https://onepoint.onesrc.workers.dev/system/list_password_is_456/ 下面有一个`.password=*`的密码文件，但除了管理员，没人能在文件列表里面看到它。
如果直接输入url，还是可以访问到这个文件的。https://onepoint.onesrc.workers.dev/system/list_password_is_456/.password=456

如果想要彻底隐藏文件，可以使用hidden。hidden隐藏的文件，不会出现在列表里面，也不能通过url访问。（管理员除外）


和改用读取 .password 文件内容相比，二者在安全性上几乎没有区别；在效率上前者还高于后者，后者多了一次访问文件内容的过程。如果是云函数之类的运行环境，前者还是更合适些。

当然，前者也是有缺点的。如果文件数多于200，需要分页时，有可能`.password=*`文件都在第二页，第一页检测不到密码文件，进而导致密码失效。
