### ISSUE TITLE
onedrive 中 使用 share_url 配置的打不开

### ISSUE THREAD

**Issue by dlytang** [ukuq/onepoint#27]
onedrive 中 使用 share_url 配置的打不开，DemoSite中的也是
都会提示
`{
  "error": "ModuleError",
  "data": {
    "msg": "This sharing link has been canceled"
  },
  "message": "模块内部发生了错误,This sharing link has been canceled"
}`

**Comment by ukuq** [comment]
去除了axios请求库依赖

重写了请求库，手动处理重定向

https://github.com/ukuq/onepoint/blob/133929aa90ef6fe878c19f917a37da03f7168b83/lib/utils/tiny-request/browser-fetch.js#L15

https://onepoint.onesrc.workers.dev/onedrive/onedrive-shareurl-cn/

已经可以正常打开了

**Comment by dlytang** [comment]
感谢
