### ISSUE TITLE
Microsoft 365 E5 续期

### ISSUE THREAD

**Issue by kamasylvia** [ukuq/onepoint#28]
OnePoint 可以通过调用 API 以续期 E5 吗？ OneIndex 和 OneManager 网上都有教程，OnePoint 的没找到。

**Comment by ukuq** [comment]
暂时不会考虑这个

**Comment by ChenYFan** [comment]
> OnePoint 可以通过调用 API 以续期 E5 吗？ OneIndex 和 OneManager 网上都有教程，OnePoint 的没找到。


自行修改https://github.com/ukuq/onepoint/blob/master/lib/routers/onedrive.js#L265，然后webpack打包即可，不过我建议作者弄成KV存好点

**Comment by ukuq** [comment]
Microsoft 365 E5 续期不在本项目考虑范围之内

另，如果需要，添加 onedrive 时可以在配置项中使用自己的 client_id、client_secret
