### ISSUE TITLE
默认用户名和密码怎么修改

### ISSUE THREAD

**Issue by kamasylvia** [ukuq/onepoint#29]
我用的是 cf workers 版本。

在 admin 帐户登录之后，点 “更多设置” -> “密码设置” -> “修改密码”，输入旧密码和新密码，确定后显示 "success"。然后 Logout 重登，新密码无效，还是要用默认的 admin 密码才行。

请问怎么设置 admin 密码，还有能建立除了 admin 之外的其他用户吗？

**Comment by ukuq** [comment]
#32 合并说明
