### ISSUE TITLE
无法访问sharepoint中的中文名称文件夹

### ISSUE THREAD

**Issue by cnc233** [ukuq/onepoint#3]
sharepoint使用中文名称的文件夹 不能正常访问
映射路径如果使用中文也无法访问

**Comment by ukuq** [comment]
https://service-8pduizwk-1255607810.ap-hongkong.apigateway.myqcloud.com/release/onePoint/ms_od_sharepoint/%E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6/%E6%96%87%E6%A1%A3.docx?&preview
刚试了一下，中文也是可以访问的。建议posRawDir先留空再试。

**Comment by cnc233** [comment]
> 
> 
> https://service-8pduizwk-1255607810.ap-hongkong.apigateway.myqcloud.com/release/onePoint/ms_od_sharepoint/%E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6/%E6%96%87%E6%A1%A3.docx?&preview
> 刚试了一下，中文也是可以访问的。建议posRawDir先留空再试。

根目录如果是中文命名的 好像会有这个问题

**Comment by ukuq** [comment]
未发现问题, 参考这个 
"/githubtest/": {
            "funcName": "ms_od_sharepoint",
            "spConfig": {
                "shareUrl": "https://lovelearn-my.sharepoint.com/:f:/g/personal/admin_share_onesrc_cc/ErxSEX2Je5tAjgK_fOP8NKoBb1KHrUBiDcz5al5q6BBQQw?e=sh6MK0",
                "postRawDir": "/中文"
            }
        }

**Comment by cnc233** [comment]
还是不行 我的程序是部署在zeit.co上的
会不会和这个有关系

**Comment by cnc233** [comment]
找到问题了
https://github.com/ukuq/onepoint/blob/22f958faa0bf947e31f2c9b9b0064a0c964657c3/bin/index_now.js#L16
修改为p_12: decodeURIComponent(url.parse(req.url).pathname)
