### ISSUE TITLE
[BUG]密码无法修改|[建议]能否更改用户名?|[建议]支持百度网盘

### ISSUE THREAD

**Issue by ChenYFan** [ukuq/onepoint#32]
提交修改密码后会提示success,然后KV里面的users:admins的密码没有改变.

并且我无法更改我的用户名,目前推测用户名键值是直接查找admin所导致的

**Comment by ChenYFan** [comment]
另外,没看懂这一行:
https://github.com/ukuq/onepoint/blob/master/lib/middleware/admin.js#L128

这是现在修改密码还没开发号吗?

**Comment by ChenYFan** [comment]
另外这是百度网盘的支持项目
**https://github.com/wx-io/PanList**

**Comment by ukuq** [comment]
- 密码修改失败的bug，是因为误将原密码作为新密码保存，已修复该问题

https://github.com/ukuq/onepoint/blob/133929aa90ef6fe878c19f917a37da03f7168b83/lib/middleware/admin.js#L153

- 用户名和salt仅支持在首次配置时修改，后续如果需要修改，可通过修改配置文件完成

- 百度云限速，且开发环境不够友好，如需百度云支持，请自行编写相关模块

**Comment by ChenYFan** [comment]
ok，谢谢
