### ISSUE TITLE
你好，我想问下支持世纪互联版的onedrive吗？还有用cloudflare可以搭建吗

### ISSUE THREAD

**Issue by awsl233** [ukuq/onepoint#4]
你好，我想问下支持世纪互联版的onedrive吗？还有用cloudflare可以搭建吗

**Comment by ukuq** [comment]
世纪互联和国际版用的api基本一样，改起来也不麻烦。只是现在没有账号，以后在说吧。至于cloudflare，可以搭建，但毕竟麻烦，不适用于小白，所以暂不考虑。
