### ISSUE TITLE
我想要自己注册应用

### ISSUE THREAD

**Issue by Micraow** [ukuq/onepoint#40]
我想要使用我自己注册的应用，来挂载onedrive ，请问重定向uri或其它什么选项有特殊的要求吗？

**Comment by ukuq** [comment]
如果使用自己注册的应用，就说明你对OneDrive这一套oauth2的认证逻辑非常熟悉了！

重定向url是什么不是很重要，真正重要的是refresh_token和对应的client信息

如果使用自己的client，你必须想办法自己获取对应的refresh_token，然后把它们一并填入到配置中！

具体不赘述，可自行查看OneDrive graph文档！

**Comment by Micraow** [comment]
好的，谢谢，我已成功。
