### ISSUE TITLE
Onedrive挂载视频无法播放

### ISSUE THREAD

**Issue by Wilnk** [ukuq/onepoint#45]
环境是用CloudFlare的 Workers 构建、构建一切顺利，但测试的时候出现视频播放失败。

是不是太大的视频无法加载还是什么情况、三四百M的视频文件偶尔可以播放，但超过五六百M的或者1G以上的就不行的。挂梯子也不行

麻烦问下大佬这是什么情况？是属于正常情况吗？

地址：https://onpoint.gaolao.workers.dev/

![image](https://user-images.githubusercontent.com/46810638/160246919-1ca44d88-3c62-48a9-b33b-2db71b25bfae.png)

**Comment by ukuq** [comment]
https://onpoint.gaolao.workers.dev/%E6%98%8E%E6%98%9F%E5%A4%A7%E4%BE%A6%E6%8E%A2/S7/01.28%E6%9C%9F%E5%A4%A7%E4%BE%A6%E6%8E%A2%E7%AC%AC%E4%B8%83%E5%AD%A3%20%E8%B6%85%E5%89%8D%E8%81%9A%E4%BC%9A%EF%BC%9A%E4%BE%A6%E6%8E%A2%E8%80%81%E5%8F%8B%E8%AE%B0%20%E4%BD%95%E7%82%85%E7%BB%84%E5%B1%80%E8%80%83%E9%AA%8C%E7%8E%A9%E5%AE%B6%E7%8E%8B%E9%B8%A5%E9%AD%8F%E6%99%A8%E6%9D%A8%E8%93%89%E9%99%B7%E5%8D%B1%E6%9C%BA%EF%BC%9F%E5%BE%AE%E5%8D%9A@%E8%BF%BD%E5%89%A7%E9%98%BF%E4%B9%90%E4%B9%90.mp4?preview

播放不出来是Dplayer的问题，这个是1.90 GB的文件，也能正常播放，至于你提到的无法播放的问题，应该是源文件或者微软服务器的问题

**Comment by Wilnk** [comment]
原来如此、谢谢大佬
