### ISSUE TITLE
scf部署错误

### ISSUE THREAD

**Issue by 1621391916** [ukuq/onepoint#7]
部署完毕后，点开其中一个映射目录，出现如下代码：
{"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Cannot read property 'password' of undefined\nTypeError: Cannot read property 'password' of undefined\n    at handleEvent (/var/user/bin/main.js:197:19)\n    at OnePoint.handleEvent (/var/user/bin/main.js:43:22)\n    at exports.main_handler (/var/user/bin/index_scf.js:36:21)\n    at EventHandler.exports.main_handler [as realHandler] (/var/user/index.js:6:56)\n    at EventHandler.handle (/var/runtime/node8/bootstrap.js:402:28)\n    at invoke (/var/runtime/node8/bootstrap.js:205:22)\n    at Timeout.setTimeout [as _onTimeout] (/var/runtime/node8/bootstrap.js:137:9)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)"}

全部五个盘都是如此

**Comment by ukuq** [comment]
猜测可能是配置文件的问题。具体如何需要提供一下详细的日志信息，日志可以在scf的控制台获取。

**Comment by 1621391916** [comment]
> 猜测可能是配置文件的问题。具体如何需要提供一下详细的日志信息，日志可以在scf的控制台获取。

返回数据:

{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Cannot read property 'password' of undefined\nTypeError: Cannot read property 'password' of undefined\n    at handleEvent (/var/user/bin/main.js:197:19)\n    at OnePoint.handleEvent (/var/user/bin/main.js:43:22)\n    at exports.main_handler (/var/user/bin/index_scf.js:36:21)\n    at EventHandler.exports.main_handler [as realHandler] (/var/user/index.js:6:56)\n    at EventHandler.handle (/var/runtime/node8/bootstrap.js:402:28)\n    at invoke (/var/runtime/node8/bootstrap.js:205:22)\n    at Timeout.setTimeout [as _onTimeout] (/var/runtime/node8/bootstrap.js:137:9)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)"}

日志:

START RequestId: 0ff1ed7b95812d177d88bef29538b3ab

Event RequestId: 0ff1ed7b95812d177d88bef29538b3ab

2020-03-21T13:54:10.196Z 0ff1ed7b95812d177d88bef29538b3ab start_time:2020-3-21 13:54:10 utf-8

2020-03-21T13:54:10.196Z 0ff1ed7b95812d177d88bef29538b3ab { method: 'GET',

  url: '/OnePoint/wangyuye@nCoV.office.gy/?',

  headers: 

   { accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',

     host: 'service-hsz22g5m-1258420821.hk.apigw.tencentcs.com',

     'sec-fetch-dest': 'document',

     'x-b3-traceid': '0ff1ed7b95812d177d88bef29538b3ab',

     'upgrade-insecure-requests': '1',

     'accept-language': 'zh-CN,zh;q=0.9',

     connection: 'keep-alive',

     'x-api-requestid': '0ff1ed7b95812d177d88bef29538b3ab',

     referer: 'https://service-hsz22g5m-1258420821.hk.apigw.tencentcs.com/release/OnePoint',

     'x-qualifier': '$LATEST',

     'endpoint-timeout': '15',

     'accept-encoding': 'gzip, deflate, br',

     'sec-fetch-mode': 'navigate',

     'x-anonymous-consumer': 'true',

     'sec-fetch-user': '?1',

     'sec-fetch-site': 'same-origin',

     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36' },

  body: {},

  adapter: 'scf',

  sourceIp: '115.203.202.212',

  query: {},

  cookie: {},

  splitPath: 

   { ph: '//service-hsz22g5m-1258420821.hk.apigw.tencentcs.com',

     p0: '/release/OnePoint',

     p_12: '/wangyuye@nCoV.office.gy/' },

  start_time: 2020-03-21T13:54:10.195Z }

2020-03-21T13:54:10.196Z 0ff1ed7b95812d177d88bef29538b3ab p_12:/wangyuye@nCoV.office.gy/

2020-03-21T13:54:10.196Z 0ff1ed7b95812d177d88bef29538b3ab drivePath:/wangyuye@nCoV.office.gy/, p2:/

TypeError: Cannot read property 'password' of undefined

    at handleEvent (/var/user/bin/main.js:197:19)

    at OnePoint.handleEvent (/var/user/bin/main.js:43:22)

    at exports.main_handler (/var/user/bin/index_scf.js:36:21)

    at EventHandler.exports.main_handler [as realHandler] (/var/user/index.js:6:56)

    at EventHandler.handle (/var/runtime/node8/bootstrap.js:402:28)

    at invoke (/var/runtime/node8/bootstrap.js:205:22)

    at Timeout.setTimeout [as _onTimeout] (/var/runtime/node8/bootstrap.js:137:9)

    at ontimeout (timers.js:475:11)

    at tryOnTimeout (timers.js:310:5)

    at Timer.listOnTimeout (timers.js:270:5) 

ERROR RequestId:0ff1ed7b95812d177d88bef29538b3ab Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Cannot read property 'password' of undefined\nTypeError: Cannot read property 'password' of undefined\n    at handleEvent (/var/user/bin/main.js:197:19)\n    at OnePoint.handleEvent (/var/user/bin/main.js:43:22)\n    at exports.main_handler (/var/user/bin/index_scf.js:36:21)\n    at EventHandler.exports.main_handler [as realHandler] (/var/user/index.js:6:56)\n    at EventHandler.handle (/var/runtime/node8/bootstrap.js:402:28)\n    at invoke (/var/runtime/node8/bootstrap.js:205:22)\n    at Timeout.setTimeout [as _onTimeout] (/var/runtime/node8/bootstrap.js:137:9)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)"} 

END RequestId: 0ff1ed7b95812d177d88bef29538b3ab

Report RequestId: 0ff1ed7b95812d177d88bef29538b3ab Duration:1ms Memory:128MB MemUsage:73.074219MB

**Comment by ukuq** [comment]
>映射路径
>映射路径是需要映射的路径，类似于 linux 里面的 mount 操作，可以映射为任意类型的路径。但需要注意，不能使用 /admin/.*， /api/.* ， /tmp/.* 三个保留路径。格式为 /xxx/。只要你愿意，映射路径甚至可以为 /a/b/c/d/ ，但要注意必须保证开头和结尾均为 /。
config.json 文件有问题, 另外注意修改管理员账号密码, 我刚试了一下登进去了

**Comment by 1621391916** [comment]
> > 映射路径
> > 映射路径是需要映射的路径，类似于 linux 里面的 mount 操作，可以映射为任意类型的路径。但需要注意，不能使用 /admin/._， /api/._ ， /tmp/.* 三个保留路径。格式为 /xxx/。只要你愿意，映射路径甚至可以为 /a/b/c/d/ ，但要注意必须保证开头和结尾均为 /。
> > config.json 文件有问题, 另外注意修改管理员账号密码, 我刚试了一下登进去了

好了，谢谢大佬
