### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by 1621391916** [ukuq/onepoint#8]
配置文件里有设置管理员账号密码，但找了半天没看到教程里说从哪里进管理界面？是我眼瞎了？

**Comment by 1621391916** [comment]
还有，就是映射目录的设置有些问题。

如果我写/a/那就没什么问题，但是我想映射到子目录，于是我写成/1/a/，按照你写的教程似乎没问题，但是点开目录就会发生错误，

scf上提示：
{"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Cannot read property 'password' of undefined\nTypeError: Cannot read property 'password' of undefined\n    at handleEvent (/var/user/bin/main.js:197:19)\n    at OnePoint.handleEvent (/var/user/bin/main.js:43:22)\n    at exports.main_handler (/var/user/bin/index_scf.js:36:21)\n    at EventHandler.exports.main_handler [as realHandler] (/var/user/index.js:6:56)\n    at EventHandler.handle (/var/runtime/node8/bootstrap.js:402:28)\n    at invoke (/var/runtime/node8/bootstrap.js:205:22)\n    at Timeout.setTimeout [as _onTimeout] (/var/runtime/node8/bootstrap.js:137:9)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)"}

服务器上就显示一个error

是我写的方式有问题？
![批注 2020-03-28 212510](https://user-images.githubusercontent.com/42343279/77824064-b65fe080-713a-11ea-97b5-ee67a2d5fe2a.png)

**Comment by ukuq** [comment]
e4475dc 已修复该项
